### ISSUE TITLE
Missing ocamlbuild and ocamlfind

### ISSUE THREAD

**Issue by ThibaultNocchi** [lascar-pacagi/MiniJava#1]
Hello Sir,

When using your Linux instructions to setup the build env, once we reach the `make` part, there is an error saying that ocamlbuild is missing. Once installed, there is also an error about ocamlfind.

I fixed it by using `opam install -y ocamlbuild ocamlfind` before making, is it because I missed a step, or maybe it should be added to the README?

Thanks!

**Comment by lascar-pacagi** [comment]
thanks Thibault!
